### ISSUE TITLE
A lilbit more docs please : )

### ISSUE THREAD

**Issue by Birowsky** [jeromedecoster/sharp-lambda-layer#1]
In particular, I'm interested in how to use this prepacked layer in a CDK or CloudFormation setup. Thanx!

**Comment by jeromedecoster** [comment]
Hi,
It simply generate a zip file to use as Lambda Layer.

Good article : https://medium.com/@anjanava.biswas/nodejs-runtime-environment-with-aws-lambda-layers-f3914613e20e
Good video : https://www.youtube.com/watch?v=5a2LS7gNECk

Upload the zip to S3, then in the Lambda console, create the shared layer...

I don't use CDK or CloudFormation. I prefer Terraform.

This Terraform script upload a zip and create the Lambda layer : https://github.com/jeromedecoster/aws-s3-notification-rekognition-imagemagick/blob/master/terraform/s3.tf
